var assetsMng = new AssetsManager();
        assetsMng.loadImage("hero", "assets/hero.png");
        assetsMng.loadImage("hud", "assets/hud.png");
        assetsMng.loadImage("bluemoon", "assets/bluemoon.png");
        assetsMng.loadImage("mana", "assets/mana.png");
        assetsMng.loadImage("bruxa", "assets/bruxa.png");
        assetsMng.loadImage("heart", "assets/heart.png");
        assetsMng.loadImage("heart2", "assets/heart2.png");
        assetsMng.loadImage("manaHeart", "assets/manaHeart.png");
        assetsMng.loadImage("dad", "assets/dad.png");
        assetsMng.loadImage("people", "assets/people.png");
        assetsMng.loadImage("flame", "assets/flame.png");
        assetsMng.loadImage("flame2", "assets/flame2.png");
        assetsMng.loadImage("object", "assets/object.png");
        assetsMng.loadImage("cenario", "assets/cenario.png");
        assetsMng.loadImage("lava", "assets/lava.png");
        assetsMng.loadImage("monster", "assets/monster.png");
        assetsMng.loadImage("expressoes", "assets/expressoes.png");
        assetsMng.loadImage("explosion", "assets/explosion.png");
        assetsMng.loadAudio("explosion", "assets/explosion.mp3");
        assetsMng.loadImage("sword", "assets/sword.png");
        assetsMng.loadImage("crystal", "assets/crystal.png");
        assetsMng.loadImage("key_0", "assets/key_0.png");
        assetsMng.loadImage("key_1", "assets/key_1.png");
        assetsMng.loadImage("key_2", "assets/key_2.png");
        assetsMng.loadImage("key_3", "assets/key_3.png");
        assetsMng.loadImage("key_4", "assets/key_4.png");
        assetsMng.loadImage("key_5", "assets/key_5.png");
        assetsMng.loadImage("key_6", "assets/key_6.png");
        assetsMng.loadImage("key_7", "assets/key_7.png");
        assetsMng.loadImage("door_0", "assets/door_0.png");
        assetsMng.loadImage("door_1", "assets/door_1.png");
        assetsMng.loadImage("door_2", "assets/door_2.png");
        assetsMng.loadImage("door_3", "assets/door_3.png");
        assetsMng.loadImage("door_4", "assets/door_4.png");
        assetsMng.loadImage("door_5", "assets/door_5.png");
        assetsMng.loadImage("door_6", "assets/door_6.png");
        assetsMng.loadImage("door_7", "assets/door_7.png");
        assetsMng.loadImage("gear", "assets/gear.png");
        assetsMng.loadImage("dungeon", "assets/dungeon.png");
        assetsMng.loadImage("switch", "assets/switch.png");
        assetsMng.loadImage("gargoyle", "assets/gargoyle.png");
        assetsMng.loadImage("box_false", "assets/box_false.png");
        assetsMng.loadImage("box_true", "assets/box_true.png");
        assetsMng.loadAudio("sword", "assets/sword.ogg");
        assetsMng.loadAudio("sword2", "assets/sword2.ogg");
        assetsMng.loadAudio("explosion", "assets/explosion.mp3");
        assetsMng.loadAudio("shot", "assets/fire.ogg");
        assetsMng.loadAudio("damage", "assets/damage.ogg");
        assetsMng.loadAudio("gameover", "assets/gameover.ogg");
        assetsMng.loadAudio("quest", "assets/quest.ogg");
        assetsMng.loadAudio("heal", "assets/heal.ogg");
        assetsMng.loadAudio("darkness", "assets/darkness.ogg");
        assetsMng.loadAudio("earth", "assets/earth.ogg");
        assetsMng.loadAudio("door", "assets/door.ogg");
        assetsMng.loadAudio("earth2", "assets/earth2.ogg");
        assetsMng.loadAudio("tema1", "assets/tema1.mp3")
        assetsMng.loadAudio("tema2", "assets/tema2.mp3")
        assetsMng.loadAudio("tema3", "assets/tema3.mp3")
        assetsMng.loadAudio("key", "assets/key.ogg")
        assetsMng.loadAudio("switchOn", "assets/switch.ogg")
        assetsMng.loadAudio("switchOn2", "assets/switch2.ogg")
        assetsMng.loadAudio("magic", "assets/magic.ogg")
        assetsMng.loadAudio("cancel", "assets/cancel.ogg")
        assetsMng.loadAudio("water", "assets/water.ogg")
        assetsMng.loadAudio("spike", "assets/spike.ogg")
        assetsMng.loadAudio("boss", "assets/boss.mp3")